### ISSUE TITLE
[Crash Report] Nullpointer Exception from the Breeder 

### ISSUE THREAD

**Issue by Allimon** [websitenmaker12/Advanced-Genetics#64]
I have encountered a server and client crashing error with the DNA breeder. I only have my client's crash report, however. It may be due to the splitter creating a bad gene cell, which when put into the breeder while it is breeding causes an issue. Here's the log:

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 3/14/14 6:14 PM
Description: Ticking tile entity

java.lang.NullPointerException
    at com.advGenetics.TileEntity.TileEntityDNABreeder.func_70316_g(TileEntityDNABreeder.java:204)
    at net.minecraft.world.World.func_72939_s(World.java:2209)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1921)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.advGenetics.TileEntity.TileEntityDNABreeder.func_70316_g(TileEntityDNABreeder.java:204)

-- Tile entity being ticked --
Details:
    Name: tileentitydnabreeder // com.advGenetics.TileEntity.TileEntityDNABreeder
    Block type: ID #715 (tile.dnaBreeder // com.advGenetics.Blocks.BlockDNABreeder)
    Block data value: 3 / 0x3 / 0b0011
    Block location: World: (1156,63,-2101), Chunk: (at 4,3,11 in 72,-132; contains blocks 1152,0,-2112 to 1167,255,-2097), Region: (2,-5; contains chunks 64,-160 to 95,-129, blocks 1024,0,-2560 to 1535,255,-2049)
    Actual block type: ID #715 (tile.dnaBreeder // com.advGenetics.Blocks.BlockDNABreeder)
    Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2209)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [GCCorePlayerSP['allimon'/17253, l='MpServer', x=1155.13, y=66.40, z=-2104.35]]
    Chunk stats: MultiplayerChunkCache: 5
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (654,68,-873), Chunk: (at 14,4,7 in 40,-55; contains blocks 640,0,-880 to 655,255,-865), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,0,-1024 to 1023,255,-513)
    Level time: 27779561 game time, 15078250 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 92 total; [EntityMinecartChest['entity.MinecartChest.name'/17480, l='MpServer', x=1132.50, y=38.50, z=-2059.50], EntityMinecartChest['entity.MinecartChest.name'/17481, l='MpServer', x=1192.50, y=26.34, z=-2057.09], EntityCow['Cow'/17482, l='MpServer', x=1188.03, y=72.00, z=-2059.91], EntityMinecartChest['entity.MinecartChest.name'/17485, l='MpServer', x=1161.13, y=33.34, z=-2042.59], EntityMinecartChest['entity.MinecartChest.name'/17486, l='MpServer', x=1109.50, y=34.50, z=-2063.50], EntityMinecartChest['entity.MinecartChest.name'/17472, l='MpServer', x=1142.50, y=38.50, z=-2052.50], GCCorePlayerSP['allimon'/17253, l='MpServer', x=1155.13, y=66.40, z=-2104.35], EntityMinecartChest['entity.MinecartChest.name'/17473, l='MpServer', x=1180.50, y=39.50, z=-2144.50], EntityMinecartChest['entity.MinecartChest.name'/17474, l='MpServer', x=1206.50, y=13.34, z=-2120.50], EntityItem['item.item.Chisel:iceshard'/17476, l='MpServer', x=1201.88, y=29.13, z=-2089.13], EntityMinecartChest['entity.MinecartChest.name'/17478, l='MpServer', x=1123.25, y=41.34, z=-2056.50], EntityMinecartChest['entity.MinecartChest.name'/17479, l='MpServer', x=1134.50, y=38.50, z=-2058.50], EntityCow['Cow'/17321, l='MpServer', x=1140.61, y=53.00, z=-2087.62], EntityCow['Cow'/17320, l='MpServer', x=1139.47, y=53.00, z=-2083.47], EntityCow['Cow'/17323, l='MpServer', x=1146.56, y=53.00, z=-2089.09], EntityCow['Cow'/17322, l='MpServer', x=1143.49, y=53.00, z=-2086.28], EntityCow['Cow'/17325, l='MpServer', x=1145.78, y=53.00, z=-2088.75], EntityCow['Cow'/17324, l='MpServer', x=1147.03, y=53.00, z=-2087.71], EntityCow['Cow'/17313, l='MpServer', x=1144.53, y=53.00, z=-2086.94], EntityCow['Cow'/17312, l='MpServer', x=1143.46, y=53.00, z=-2084.57], EntityCow['Cow'/17315, l='MpServer', x=1139.47, y=53.00, z=-2084.59], EntityCow['Cow'/17314, l='MpServer', x=1142.51, y=53.00, z=-2085.19], EntityCow['Cow'/17317, l='MpServer', x=1140.47, y=53.00, z=-2086.21], EntityCow['Cow'/17316, l='MpServer', x=1140.70, y=53.00, z=-2086.06], EntityCow['Cow'/17319, l='MpServer', x=1143.34, y=53.00, z=-2088.53], EntityMinecartChest['entity.MinecartChest.name'/17494, l='MpServer', x=1216.50, y=45.50, z=-2151.50], EntityCow['Cow'/17318, l='MpServer', x=1143.26, y=53.00, z=-2088.53], EntityCow['Cow'/17306, l='MpServer', x=1144.53, y=53.00, z=-2084.52], EntityCow['Cow'/17307, l='MpServer', x=1140.65, y=53.00, z=-2088.53], EntityCow['Cow'/17304, l='MpServer', x=1139.47, y=53.00, z=-2087.07], EntityCow['Cow'/17305, l='MpServer', x=1140.66, y=53.00, z=-2085.14], EntityCow['Cow'/17310, l='MpServer', x=1140.53, y=53.00, z=-2083.47], EntityCow['Cow'/17311, l='MpServer', x=1142.32, y=53.00, z=-2088.53], EntityCow['Cow'/17308, l='MpServer', x=1141.82, y=53.00, z=-2087.32], EntityCow['Cow'/17309, l='MpServer', x=1143.48, y=53.00, z=-2083.47], EntityCow['Cow'/17298, l='MpServer', x=1139.47, y=53.00, z=-2088.53], EntityCow['Cow'/17299, l='MpServer', x=1141.50, y=53.00, z=-2084.63], EntityCow['Cow'/17296, l='MpServer', x=1143.41, y=53.00, z=-2087.31], EntityCow['Cow'/17297, l='MpServer', x=1140.92, y=53.00, z=-2084.65], EntityCow['Cow'/17302, l='MpServer', x=1142.07, y=53.00, z=-2083.47], EntityCow['Cow'/17303, l='MpServer', x=1144.53, y=53.00, z=-2085.69], EntityCow['Cow'/17300, l='MpServer', x=1142.27, y=53.00, z=-2086.69], EntityCow['Cow'/17301, l='MpServer', x=1140.37, y=53.00, z=-2087.46], EntityCow['Cow'/17291, l='MpServer', x=1144.53, y=53.00, z=-2084.46], EntityCow['Cow'/17290, l='MpServer', x=1144.53, y=53.00, z=-2088.53], EntityCow['Cow'/17289, l='MpServer', x=1141.99, y=53.00, z=-2088.53], EntityCow['Cow'/17288, l='MpServer', x=1139.47, y=53.00, z=-2085.40], EntityCow['Cow'/17295, l='MpServer', x=1144.53, y=53.00, z=-2087.46], EntityCow['Cow'/17294, l='MpServer', x=1142.79, y=53.00, z=-2086.38], EntityCow['Cow'/17293, l='MpServer', x=1139.47, y=53.00, z=-2088.53], EntityCow['Cow'/17292, l='MpServer', x=1144.53, y=53.00, z=-2083.47], EntityCow['Cow'/17283, l='MpServer', x=1141.96, y=53.00, z=-2083.47], EntityCow['Cow'/17282, l='MpServer', x=1144.53, y=53.00, z=-2088.53], EntityCow['Cow'/17281, l='MpServer', x=1139.47, y=53.00, z=-2083.47], EntityCow['Cow'/17280, l='MpServer', x=1139.47, y=53.00, z=-2083.47], EntityCow['Cow'/17287, l='MpServer', x=1144.53, y=53.00, z=-2085.78], EntityCow['Cow'/17286, l='MpServer', x=1139.47, y=53.00, z=-2086.23], EntityCow['Cow'/17285, l='MpServer', x=1139.47, y=53.00, z=-2087.09], EntityCow['Cow'/17284, l='MpServer', x=1139.47, y=53.00, z=-2086.57], EntityCow['Cow'/17269, l='MpServer', x=1140.93, y=53.00, z=-2083.47], EntityMinecartChest['entity.MinecartChest.name'/17268, l='MpServer', x=1142.19, y=32.34, z=-2091.50], EntityCow['Cow'/17271, l='MpServer', x=1139.47, y=53.00, z=-2088.53], EntityCow['Cow'/17270, l='MpServer', x=1141.95, y=53.00, z=-2086.17], EntitySheep['Sheep'/17264, l='MpServer', x=1149.53, y=68.00, z=-2113.13], EntityMinecartChest['entity.MinecartChest.name'/17267, l='MpServer', x=1136.50, y=32.34, z=-2090.28], EntityCow['Cow'/17277, l='MpServer', x=1143.39, y=53.00, z=-2086.66], EntityCow['Cow'/17276, l='MpServer', x=1142.04, y=53.00, z=-2084.57], EntityCow['Cow'/17279, l='MpServer', x=1143.46, y=53.00, z=-2088.53], EntityCow['Cow'/17278, l='MpServer', x=1140.84, y=53.00, z=-2088.53], EntityCow['Cow'/17273, l='MpServer', x=1141.69, y=53.00, z=-2085.65], EntityCow['Cow'/17272, l='MpServer', x=1140.61, y=53.00, z=-2088.53], EntityCow['Cow'/17275, l='MpServer', x=1143.37, y=53.00, z=-2084.57], EntityCow['Cow'/17274, l='MpServer', x=1142.23, y=53.00, z=-2087.45], EntityItem['item.tile.mfr.rubberwood.sapling'/17254, l='MpServer', x=1159.16, y=72.13, z=-2104.56], EntityItem['item.tile.mfr.rubberwood.sapling'/17255, l='MpServer', x=1161.22, y=72.13, z=-2101.66], EntityItem['item.tile.mfr.rubberwood.sapling'/17260, l='MpServer', x=1161.88, y=72.13, z=-2105.94], EntityItem['item.item.charcoal'/17261, l='MpServer', x=1146.50, y=55.13, z=-2104.50], EntityItem['item.item.charcoal'/17262, l='MpServer', x=1146.50, y=55.13, z=-2104.50], EntityMinecartChest['entity.MinecartChest.name'/17263, l='MpServer', x=1142.50, y=32.34, z=-2121.66], EntityItem['item.tile.mfr.rubberwood.sapling'/17256, l='MpServer', x=1162.59, y=72.13, z=-2108.88], EntityItem['item.tile.mfr.rubberwood.sapling'/17257, l='MpServer', x=1158.59, y=72.13, z=-2108.09], EntityItem['item.tile.mfr.rubberwood.sapling'/17258, l='MpServer', x=1158.13, y=72.13, z=-2104.22], EntityItem['item.tile.mfr.rubberwood.sapling'/17259, l='MpServer', x=1162.44, y=69.13, z=-2104.88], EntityFrienderman['Enderman'/17471, l='MpServer', x=1126.47, y=64.00, z=-2139.47], EntityMinecartChest['entity.MinecartChest.name'/17470, l='MpServer', x=1135.91, y=43.34, z=-2077.53], EntityMinecartChest['entity.MinecartChest.name'/17469, l='MpServer', x=1131.50, y=42.50, z=-2071.50], EntityEnderman['Enderman'/17468, l='MpServer', x=1128.50, y=22.00, z=-2067.50], EntityFrienderman['Enderman'/17467, l='MpServer', x=1124.91, y=19.00, z=-2070.72], EntityMinecartChest['entity.MinecartChest.name'/17466, l='MpServer', x=1145.50, y=32.50, z=-2129.50], EntityMinecartChest['entity.MinecartChest.name'/17465, l='MpServer', x=1188.50, y=29.34, z=-2107.50], EntityFrienderman['Enderman'/17464, l='MpServer', x=1155.34, y=24.00, z=-2138.53], EntityEnderman['Enderman'/17463, l='MpServer', x=1172.34, y=76.00, z=-2120.84]]
    Retry entities: 0 total; []
    Server brand: mcpc,craftbukkit,fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:440)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2312)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:856)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_11, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 749043864 bytes (714 MB) / 1623130112 bytes (1547 MB) up to 3817799680 bytes (3640 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -XX:MaxPermSize=256m
    AABB Pool Size: 5536 (310016 bytes; 0 MB) allocated, 5536 (310016 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 113 mods loaded, 113 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML{6.4.49.965} [Forge Mod Loader](modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge{9.11.1.965} [Minecraft Forge](modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CodeChickenCore{0.9.0.9} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NotEnoughItems{1.6.1.9} [Not Enough Items](notenoughitems 1.6.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenModsCore{0.2} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    PowerCrystalsCore{1.1.8} [PowerCrystals Core](powercrystalscore-1.1.8-9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TConstruct-Preloader{0.0.1} [Tinkers Corestruct](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    advancedgenetics{v1.4.1} [Advanced Genetics](advancedgenetics_v1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ArchimedesShipsMod{1.6.4 v1.4.5} [Archimedes' Ships](archimedesships.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Artifice{1.6.4R1.1.3} [Artifice](artifice-1.1.3-243.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ArtificeCompat|EE3{1.6.4R1.1.3} [Artifice Compat: EE3](artifice-1.1.3-243.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ArtificeCompat|Forestry{1.6.4R1.1.3} [Artifice Compat: Forestry](artifice-1.1.3-243.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ArtificeCompat|Vanilla{1.6.4R1.1.3} [Artifice Compat: Vanilla](artifice-1.1.3-243.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded{1.6.2R2.7.5} [MineFactory Reloaded](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ArtificeCompat|MFR{1.6.4R1.1.3} [Artifice Compat: MFR](artifice-1.1.3-243.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ArtificeCompat|Buildcraft{1.6.4R1.1.3} [Artifice Compat: Buildcraft](artifice-1.1.3-243.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ArtificeCompat|ForgeMicroblock{1.6.4R1.1.3} [Artifice Compat: ForgeMicroblock](artifice-1.1.3-243.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ArtificeCompat|Thaumcraft{1.6.4R1.1.3} [Artifice Compat: Thaumcraft](artifice-1.1.3-243.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AutoBlocks{1.0.0} [AutoBlocks](autoblocks 1.0.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Autoutils{1.0.1} [Autoutils](autoutils-1.6.4-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    betterstorage{0.8.0.43} [BetterStorage](betterstorage-1.6.4-0.8.0.45.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Natura{2.1.14} [Natura](natura_mc1.6.X_2.1.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BiomesOPlenty{1.2.1} [Biomes O' Plenty](biomesoplenty-universal-1.6.4-1.2.1.434.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CarpentersBlocks{2.0.3} [Carpenter's Blocks](carpenter's blocks v2.0.3 - MC 1.6+.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CoFHCore{2.0.0.2} [CoFH Core](cofhcore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CoFHLoot{2.0.0.2} [CoFH Loot](cofhcore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CoFHMasquerade{2.0.0.2} [CoFH Masquerade](cofhcore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CoFHSocial{2.0.0.2} [CoFH Social](cofhcore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CoFHWorld{2.0.0.2} [CoFH World](cofhcore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ConfigMod{v1.0} [Extended Mod Config](configmod for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CoroAI{v1.0} [CoroAI](coroai for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    darwin{0.2.3} [Darwin](darwin_0.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    DragonMounts{r34} [Dragon Mounts](dragonmount_r35_mc1.6.x.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    EnhancedCore{1.1.3} [EnhancedCore](enhancedcore_1.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    EP2{1.0.9} [EnhancedPortals 2](enhancedportals-2_1.0.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ExtendedRenderer{v1.0} [Extended Renderer](extendedrenderer for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FlansMod{4.1.1} [Flans Mod](flansmod-4.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FoodPlus{2.7-PRE} [§bFood Plus](food plus mod 2.7-PRE.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    633{${mod.version}} [Fossil/Archeology: Reported](fossilsarch-reported-v1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    cfm{3.2.7} [§4MrCrayfish's Furniture Mod](furnituremodv3.2.7%281.6.4%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GalacticraftCore{2.0.10} [Galacticraft Core](galacticraft-1.6.4-2.0.10.972.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GalacticraftMars{2.0.10} [Galacticraft Mars](galacticraft-planets-1.6.4-2.0.10.972.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    hamstermod{0.1} [Hamster Mod](hamsterrific[1.6.4]V2.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    hamstersforever{1.0} [Hamsters Forever](hamstersforever-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Hats{2.1.4} [Hats](hats2.1.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    iChunUtil{2.4.0} [iChunUtil](ichunutil2.4.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ImmibisCore{57.1.93} [Immibis Core](immibis-core-57.1.93.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    inventorytweaks{1.56} [Inventory Tweaks](InventoryTweaks-MC1.6.2-1.56-b77.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    LiquidXP{57.1.1} [Liquid XP](liquid-xp-57.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MapWriter{2.0} [MapWriter](mapwriter-2.0.16.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MFR Compat Forestry Trees{1.0} [MFR Compat Forestry Trees](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MFR Compat Extra Trees{1.0} [MFR Compat Extra Trees](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatAppliedEnergistics{1.6.2R2.7.5} [MFR Compat: Applied Energistics](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatAtum{1.6.2R2.7.5} [MFR Compat: Atum](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatBackTools{1.6.2R2.7.5} [MFR Compat: BackTools](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatBuildCraft{1.6.2R2.7.5} [MFR Compat: BuildCraft](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatChococraft{1.6.2R2.7.5} [MFR Compat: Chococraft](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatExtraBiomes{1.6.2R2.7.5} [MFR Compat: ExtraBiomes](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatForestry{1.6.2R2.7.5} [MFR Compat: Forestry](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatForestryPre{1.6.2R2.7.5} [MFR Compat: Forestry (part 2)](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatForgeMicroblock{1.6.2R2.7.5} [MFR Compat: ForgeMicroblock](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatIC2{1.6.2R2.7.5} [MFR Compat: IC2](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatMystcraft{1.6.2R2.7.5} [MFR Compat: Mystcraft](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatPams{1.6.2R2.7.5} [MFR Compat: Pam's Mods](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForgeMultipart{1.0.0.244} [Forge Multipart](ForgeMultipart-universal-1.6.4-1.0.0.244.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Core{4.3.2.26} [ProjectRed](projectredbase-1.6.4-4.3.2.26.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Exploration{4.3.2.26} [ProjectRed-Exploration](projectredworld-1.6.4-4.3.2.26.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatProjRed{1.6.2R2.7.5} [MFR Compat ProjectRed](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatRailcraft{1.6.2R2.7.5} [MFR Compat: Railcraft](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatRP2{1.6.2R2.7.5} [MFR Compat: RP2](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatSufficientBiomes{1.6.2R2.7.5} [MFR Compat: Sufficient Biomes](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatThaumcraft{1.6.2R2.7.5} [MFR Compat: Thaumcraft](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThermalExpansion{3.0.0.2} [Thermal Expansion](thermalexpansion-3.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatThermalExpansion{1.6.2R2.7.5} [MFR Compat: Thermal Expansion](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatTwilightForest{1.6.2R2.7.5} [MFR Compat: TwilightForest](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatVanilla{1.6.2R2.7.5} [MFR Compat: Vanilla](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatXyCraft{1.6.2R2.7.5} [MFR Compat: XyCraft](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AS_Minions{1.7.9b} [Minions](minions_1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildMod{v1.0} [Build Mod](modbuild for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Morph{0.7.0} [Morph](morphbeta-0.7.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    necromancy{1.4c} [Necromancy](necromancy-1.4c-9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIPlugins{1.1.0.6} [NEI Plugins](neiplugins-1.1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    notenoughkeys{0.0.4} [Not Enough Keys](notenoughkeys-1.6.4-0.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenMods{0.2} [OpenMods](openmodslib-0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenBlocks{1.2.5} [OpenBlocks](openblocks-1.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Transportation{4.3.2.26} [ProjectRed-Transportation](projectredmechanical-1.6.4-4.3.2.26.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Waila{1.5.1} [Waila](waila_1.5.1a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TConstruct{1.6.X_1.5.4dev} [Tinkers' Construct](tconstruct_mc1.6.4_1.5.4d4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Compatibility{4.3.2.26} [ProjectRed-Compatibility](projectredcompat-1.6.4-4.3.2.26.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Integration{4.3.2.26} [ProjectRed-Integration](projectredintegration-1.6.4-4.3.2.26.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Transmission{4.3.2.26} [ProjectRed-Transmission](projectredintegration-1.6.4-4.3.2.26.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Illumination{4.3.2.26} [ProjectRed-Illumination](projectredlighting-1.6.4-4.3.2.26.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Expansion{4.3.2.26} [ProjectRed-Expansion](projectredmechanical-1.6.4-4.3.2.26.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    QuantumCraft{1.1} [qCraft](qcraft1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    RandomThings{1.8.9} [Random Things](random things v. 1.8.9 [MC 1.6.4].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    SaintsPack{0.5} [Saintspack](saintspack.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    secretroomsmod{4.6.2} [The SecretRoomsMod](secretroomsmod-universal-1.6.4-4.6.2.319.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Statues{2.1.1} [Statues](statues-1.6.4-2.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Sync{2.1.1} [Sync](sync2.1.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TMechworks{19.d4b8fa0} [Tinkers' Mechworks](tmechworks_mc1.6.4_0.1.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TrailMix{2.0.0} [TrailMix](trailmix2.0.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    tropicraftmod{v5.1.6 for MC 1.6.4} [Tropicraft](tropicraft v5.1.6 Mod for MC v1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    volleyballmod{v5.1.6 for MC 1.6.4} [Volleyball](tropicraft v5.1.6 Mod for MC v1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Waypoints{1.0.2} [Waypoints](waypoints-1.6.4-1.0.2fix.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AIBlock{v1.0} [AIBlock](weather v1.59 Mod for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    WeatherMod{1.58} [Weather and Tornadoes](weather v1.59 Mod for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    witchery{0.15.1} [Witchery](witchery_0-15-1_164.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    worldofdinos{1.0} [World of Dinos](worldofdinos-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Chisel{1.5.0} [Chisel](zchisel-1.6.4-1.5.0fix.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    McMultipart{1.0.0.244} [Minecraft Multipart Plugin](ForgeMultipart-universal-1.6.4-1.0.0.244.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForgeMicroblock{1.0.0.244} [Forge Microblocks](ForgeMultipart-universal-1.6.4-1.0.0.244.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TConstruct Environment: Environment seems clean, however you are using a modpack; please report it to the pack author, not us!
    Launched Version: 1.6.4-Forge9.11.1.965
    LWJGL: 2.9.0
    OpenGL: AMD Radeon HD 5700 Series GL version 4.3.12618 Compatibility Profile Context 13.251.0.0, ATI Technologies Inc.
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: Default
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 125 (7000 bytes; 0 MB) allocated, 125 (7000 bytes; 0 MB) used

**Comment by Allimon** [comment]
Removing the breeder fixes this. Also, it has to do with the occasional "Unusable gene" that is produced more often when using itemducts and/or hoppers.

**Comment by origamerpro** [comment]
too problem me. Breeder crash mcpc+ 1.6.4 # 250

**Comment by origamerpro** [comment]
pls fix that problem

**Comment by Nistis** [comment]
The thing is i cant get to my world so i cant delete the breeder. Now when i start my client it doesnt even show the world. I think it has corupted that world or something. Well and of course i didnt save my world befor doing advanced genetics stuff so i dont know how to get it back now. It was a pretty big world like 2 quarry plus already done. I dont want to start it over :( Is there a possible way of getting the world back?

**Comment by websitenmaker12** [comment]
I am doing my best to fix this annoying bug but I can't guarantee that it will work
but you can do something. You can load your world into MCEdit and delete the
breeder which causes the problem. That should help for now.

**Comment by origamerpro** [comment]
you fix that error? i dont look new version for 1.6.4.

**Comment by websitenmaker12** [comment]
I hope it is fixed...... If not, please reopen this issue.

**Comment by origamerpro** [comment]
at the moment it is not solved. work block "dnabreeder" leads to crash server. i used mcpc+ 220-251.
i all that time wait fix.

**Comment by websitenmaker12** [comment]
New version is out. I hope it fixes this.
